version: "3.8" 

services:
  mariadb:
    image: mariadb:afarachi
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

  wordpress:
    image: wordpress:afarachi
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    # restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
      
  nginx:
    image: nginx:afarachi
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
        - inception
    depends_on:
          - wordpress
          - mariadb
    restart: always



networks:
  network:
    name: inception
    driver: bridge


volumes:
  mariadb:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/afarachi/data/mariadb
      o: bind
  wordpress:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/afarachi/data/wordpress
      o: bind
